language: ruby
rvm:
  - 2.3
before_install:
  - rvm gemset use whitespectre --create
  - gem install bundler --pre
  - bundle install

services:
  - postgresql

test:
  adapter: postgresql
  database: group_events_test

before_script:
  - psql -c "CREATE DATABASE group_events_test;" -U postgres
  - psql -c "CREATE USER guille WITH PASSWORD 'root';" -U postgres

script:
  - rake db:test:prepare
  - rake db:migrate
