language: ruby
rvm:
  - 2.3
before_install:
  - rvm gemset use whitespectre --create
  - gem install bundler --pre
  - bundle install --retry=1

services:
  - postgresql

test:
  adapter: postgresql
  database: events_test

before_script:
  - psql -c "CREATE DATABASE events_test;" -U postgres
  - rake db:test:prepare
  - rake db:migrate
