language: ruby
rvm:
  - 2.3
before_install:
  - rvm gemset use whitespectre --create
  - gem install bundler --pre
  - bundle install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE events_test;" -U postgres
  - psql -c "CREATE USER guille WITH PASSWORD 'root';" -U postgres
